//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAndClient
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public string Number { get; set; }
        public string Insurance { get; set; }
        public System.DateTime DateFirts { get; set; }
        public System.DateTime Tern { get; set; }
        public string IncurancePayment { get; set; }
        public string GosNumber { get; set; }
        public string NameCar { get; set; }
    }
}
