//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDStrahEntitis : DbContext
    {
        private static BDStrahEntitis _context;
        public BDStrahEntitis()
            : base("name=BDStrahEntitis")
        {
        }

        public static BDStrahEntitis GetContext()
        {
            if (_context == null)
                _context = new BDStrahEntitis();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContractAndClient> ContractAndClient { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeStrahovaniya> TypeStrahovaniya { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
